version: "3.6"

networks:
  internal-pod:
    internal: true
  external-pod:
    internal: false

volumes:
  dolibarr-custom:
  dolibarr-docs:
  mysql-data:

services:
  dolibarr:
    image: tuxgasy/dolibarr:16.0.3
    environment:
      DOLI_DB_HOST: "mariadb"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_USER: "root"
      DOLI_DB_PASSWORD: "perseigne1"
      DOLI_DB_NAME: "perseigneUF"
      DOLI_ADMIN_LOGIN: "perseigneUF"
      DOLI_ADMIN_PASSWORD: "perseigne1"
    ports:
      - 8300:80
      - 8380:8080
      - 22:22
    restart: unless-stopped
    volumes:
      - /home/perseigneUF/dolibarr/dolibarr-docs:/var/www/documents
      - /home/perseigneUF/dolibarr/dolibarr-custom:/var/www/html/custom
    networks:
      - internal-pod
      - external-pod

  mariadb:
    image: library/mariadb:latest
    environment:
      MARIADB_DATABASE: "perseigneUF"
      MARIADB_ROOT_PASSWORD: "perseigne1"
    ports:
      - 3308:3306
    restart: unless-stopped
    volumes:
      - /home/perseigneUF/dolibarr/mysql-data:/var/lib/mysql
    networks:
      - internal-pod
      - external-pod
