version: '2'
services:
  rhasspy-en:
    image: rhasspy/rhasspy
    container_name: rhasspy-en
    restart: unless-stopped
    volumes:
      - $HOME/.config/rhasspy/profiles/profiles:/profiles
      - /etc/localtime:/etc/localtime
    ports:
      - '12102:12101'
    devices:
      - /dev/snd:/dev/snd
    command: '--user-profiles /profiles --profile en'
  rhasspy-fr:
    image: rhasspy/rhasspy
    container_name: rhasspy-fr
    restart: unless-stopped
    volumes:
      - $HOME/.config/rhasspy/profiles/profiles:/profiles
      - /etc/localtime:/etc/localtime
    ports:
      - '12101:12101'
    devices:
      - /dev/snd:/dev/snd
    command: '--user-profiles /profiles --profile fr'

